# Generated by Django 5.1.4 on 2025-03-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_delete_singupform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
