# Generated by Django 5.1.4 on 2025-03-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
