# Generated by Django 5.1.4 on 2025-08-12 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_like_unique_together_remove_like_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب های کاربری'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/images', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mli_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
