# Generated by Django X.X on YYYY-MM-DD HH:MM

from django.db import migrations

def create_missing_profiles(apps, schema_editor):
    """
    این تابع تمام کاربران بدون پروفایل را پیدا کرده و برایشان پروفایل می‌سازد.
    """
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')
    for user in User.objects.filter(profile__isnull=True):
        Profile.objects.create(user=user)

class Migration(migrations.Migration):

    # این بخش را با نام فایل مایگریشن قبلی در پوشه accounts/migrations/ جایگزین کنید
    dependencies = [
        ('accounts', '0012_alter_profile_options_alter_profile_fathers_name_and_more'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles),
    ]