# Generated by Django 5.1.7 on 2025-04-30 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_fix_missing_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
