# Generated by Django 5.1.7 on 2025-05-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTest',
        ),
    ]
