# Generated by Django 5.1.7 on 2025-05-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_mytest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/image', verbose_name='تصویر مقاله'),
        ),
    ]
